# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'AgoraChatEThreeExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'VirgilE3Kit', '2.2.0'
  pod 'Agora_Chat_iOS','1.0.6'
  pod 'ZSwiftBaseLib','0.1.4'
  pod 'ProgressHUD'
end
